---
title: "Flex Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
--- 

```{r}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(dplyr)

data("rest_inspec")

inspect = 
  rest_inspec |> 
  mutate(
    inspection_date = lubridate::ymd(inspection_date),
    year = year(inspection_date),
    month = month(inspection_date)) |> 
  select(boro, cuisine_description, inspection_date, action, critical_flag, score, grade, inspection_type, year, 
         month) |> 
  filter(cuisine_description %in% c("Thai","Spanish","Russian","Polynesian","Seafood","Pizza/Italian",
                                    "Peruvian","Pakistani","Latin","Moroccan",
                                    "Japanese","German","Chinese","French","Creole")) |> 
  drop_na() |> 
  sample_n(10000)
```


Column {data-width=650}
-----------------------------------------------------------------------
### Boxplot

Restaurant score by cuisine type in NY

```{r}
inspect |>
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) |> 
  plot_ly(x = ~cuisine_description, y = ~score, color = ~cuisine_description, 
          type = "box", colors = "viridis") |> 
  layout(title = "Boxplots of Restaurant Scores by Type of Cuisine" , plot_bgcolor = "e5ecf6", 
         xaxis = list(title = 'Type of Cuisine'), 
         yaxis = list(title = 'Restaurant Score'))
```


Column {data-width=350}
-----------------------------------------------------------------------
### Lineplot

Average restaurant score from 2013-2017 by borough in NY

```{r} 
inspect |> 
  group_by(boro,year) |> 
  summarise(mean_score = mean(score)) |> 
  plot_ly(x = ~year, y = ~mean_score, color = ~boro, type = "scatter", mode = "lines", 
          colors = "viridis") |> 
  layout(title = "Lineplot of Yearly Average Restaurant Scores by Borough" , plot_bgcolor = "e5ecf6", 
         xaxis = list(autotypenumbers = 'strict', title = 'Year'), 
         yaxis = list(title = 'Average Restaurant Score'))
```

### Barchart

Critical Violations (likely to contribute to food-borne illness) by borough in NY

```{r}
inspect |> 
  filter(boro != "Missing") |> 
  count(boro, critical_flag) |> 
  plot_ly(x = ~boro, y = ~n, type = "bar", color = ~critical_flag)|> 
  layout(title = "Barchart of Violation Type across the Boroughs" , plot_bgcolor = "e5ecf6", 
         xaxis = list(title = 'Borough'), 
         yaxis = list(title = 'Frequency'))
```


