---
title: "Resume"
output:
  html_document:
      toc: true
      toc_float: true
---

## Academic Background

### Columbia University Mailman School of Public Health
##### Master of Public Health, May 2024
* Department of Epidemiology, Certificate in Infectious Disease Epidemiology

### The College of New Jersey
##### Bachelor of Science, May 2022
* Double-major in Public Health (Social and Behavioral Health Concentration) and Mathematics (Statistics Concentration) and minor in Criminology
* Societies: Honor's Program, Phi Beta Kappa, Eta Sigma Gamma

## Research Experience

##### Analysis of Error Prevalence in Quality Assurance Reviews
* Conducted monthly QA reviews for all Bexsero charts of newly enrolled PTPs and reviewed HPTN 091 charts prior to Interim Monitoring Review by DAID and entered information about chart errors into RedCap 
* Exported data from RedCap and using SAS, utilized data visualization methods and statistical tests (Cochran's Q & McNemar's) to evaluate prevalence of error types across different studies
* Interpreted data analysis, presented to the HPC staff, and provided recommendations to minimize errors during data collection and better prepare the site before monitoring visits

##### Is Personal Protective Equipment Worth the Hassle? Annual Risk of Cryptosporidiosis to Dairy Farmers and How Personal Protective Equipment and Handwashing Can Mitigate It
* Advisor: Assistant Professor Dr. Alexis Mraz, PhD, MS
* Determined the occupational risk of cryptosporidiosis among NJ dairy farmers by developing a Quantitative Microbial Risk Assessment (QMRA) in R through the utilization of prior literature and analysis of cow feces samples
* Conducted work as a Student Assistant Researcher in the lab by collecting samples of cow feces; processing control and C. parvum spiked samples using filtration methods established in study protocols; and preparing samples for DNA analysis by the NanoDrop and qPCR machines under the supervision of the PI

##### Statistical Analysis of Simulated Snakeskins
* Advisor: Professor Dr. Ochs PhD
* Analyzed data generated by researchers at Haverford College and employed R programming to perform cluster analysis and dimensional reduction to determine the underlying parameters inherent in animal skin patterns 

##### The Public Health Applications of Twitter During the Current COVID-19 Pandemic
* Advisor: Assistant Professor Dr. Natasha Patterson PhD, MPH
* Analyzed prior research on public health applications of social media and health education models for previous pandemics
* Gathered Twitter posts throughout the COVID-19 outbreak; developed and trained topic classification and sentiment analysis models using online software, and ran data analytics on the sampled tweets
* Developed further recommendations for model enhancement and data analytics to determine effectiveness of public health education theory applications and interventions during disease outbreaks similar to COVID-19

## Professional Experience

##### *Casual Research Assistant*, **Columbia Mailman School of Public Health**, Aug 2023 - Present
* Conduct data acquisition, processing/cleaning, linkages, and utilize R programming to perform analysis to fulfill research aims 
* Conduct literature reviews; contribute (as a co-author) to manuscripts, figures, tables, slides, and other presentation materials based on study findings 
* Develop and update IRB protocols as well as contribute to new and ongoing grant proposals as needed

##### *Data Management Intern & Interim Study Coordinator*, **Harlem Prevention Center**, May 2023 - Aug 2023
* Conducted data monitoring, quality assurance, and quality control on data collected for multiple ongoing studies in preparation for future study reviews and site visits 
* Coordinated participants and conducted enrollment/exit interviews as per data collection protocols of the COVID-19 Self-testing study 
* Reviewed eligibility criteria of screened study participants for enrollment, including review of eligibility case report forms, source documents, and informed consent forms 
* Assisted with the review of all data queries and their resolution as well as submission of study forms to the statistical and data management center 
* Identified issues with data collection, reported findings to the project’s leadership, and developed appropriate corrective measures with input from the team to improve site performance and minimize errors
* Attended weekly staff meetings to discuss the progress of the studies involved and research-related issues
* Conducted all research activities in accordance with study protocol, standard operating procedures, and other appropriate institutional regulations, procedures, and policies, including procedures to safeguard the confidentiality of study participants

##### *Hunger Prevention Program Assistant*, **Arm in Arm**, May 2021 - Sep 2021
* Conducted surveys with clients at the Hudson location regarding visits prior to and during the COVID-19 pandemic
* Analyzed client intake data for the Hudson location and reported the results to the Food Pantry Team
* Reviewed social media analytics and provided recommendations to promote the organization’s presence across social media platforms
* Assisted clients in Trenton and Princeton areas struggling with food insecurity by providing groceries on-site and through home food deliveries
* Collaborated with Capital Health to provide blood pressure screenings and COVID-19 vaccines at a health screening event and provided educational brochures focused on preventative care for cardiovascular health

This is just a brief summary of my education and experiences. If you would like to learn more, you can visit my LinkedIn page by using the link below.

[LinkedIn](https://www.linkedin.com/in/nandini-mutyala/)